# pytorch_lightning==2.0.2
trainer:
  accelerator: gpu
  devices: 2
  precision: 16-mixed
  logger:
    class_path: pytorch_lightning.loggers.CSVLogger
    init_args:
      save_dir: output
      name: custom
  max_steps: 5000
  val_check_interval: 500
model:
  model_name: vit-b16-224-in21k
  training_mode: full
  optimizer: sgd
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0
  scheduler: cosine
  warmup_steps: 500
data:
  dataset: custom
  root: /kaggle/input/100-bird-species
  num_classes: 525
  size: 224
  batch_size: 128
  workers: 4
model_checkpoint:
  filename: best-step-{step}-{val_acc:.4f}
  monitor: val_acc
  save_last: true
  mode: max